package textsearchtool;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.List;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.border.EmptyBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import textsearchtool.util.DataModel;
import textsearchtool.util.FileReader;
import textsearchtool.util.SentenceDataModel;
import textsearchtool.util.searchHandler;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Bashi
 */



public class AppWindow extends javax.swing.JFrame {

    /**
     * Creates new form AppWindow
     */
    File lastOpenedFile;
    DataModel sentences;
    DataModel searchResults;
    Set<File> selectedFiles;
    

    public AppWindow() {
        initComponents();
    }
    
    private void setInitState(){
        sentences = null;
        searchResults = null;
        selectedFiles = null;
        btn_browseFile.setText("Add XML Files");
        button_search.setEnabled(false);
        label_numFiles.setVisible(false);
        label_numHits.setVisible(false);
        table_output.setVisible(false);
        table_output.setModel(null);
        table_output.removeAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_browseFile = new javax.swing.JButton();
        spinner_windowSize = new javax.swing.JSpinner();
        button_search = new javax.swing.JButton();
        label_numFiles = new javax.swing.JLabel();
        combo_search = new javax.swing.JComboBox<>();
        label_numHits = new javax.swing.JLabel();
        button_clearFiles = new javax.swing.JButton();
        panel_output = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_output = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KWIC Search Tool");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(991, 428));

        jLabel3.setText("Window size:");

        btn_browseFile.setText("Add XML Files");
        btn_browseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browseFileActionPerformed(evt);
            }
        });

        spinner_windowSize.setModel(new javax.swing.SpinnerNumberModel(5, 0, null, 1));

        button_search.setText("Search Node");
        button_search.setEnabled(false);
        button_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_searchActionPerformed(evt);
            }
        });

        combo_search.setEditable(true);
        combo_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_searchActionPerformed(evt);
            }
        });

        button_clearFiles.setText("Clear All Files");
        button_clearFiles.setEnabled(false);
        button_clearFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_clearFilesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_numHits)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_search, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_browseFile)
                                .addGap(29, 29, 29)
                                .addComponent(label_numFiles)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_clearFiles)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(spinner_windowSize, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_browseFile)
                    .addComponent(label_numFiles)
                    .addComponent(button_clearFiles))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_search)
                        .addComponent(jLabel3)
                        .addComponent(spinner_windowSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(combo_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(label_numHits))
        );

        table_output.setAutoCreateRowSorter(true);
        table_output.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Left Window", "Keyword", "Right Window", "File", "Sentence Index"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_output);

        javax.swing.GroupLayout panel_outputLayout = new javax.swing.GroupLayout(panel_output);
        panel_output.setLayout(panel_outputLayout);
        panel_outputLayout.setHorizontalGroup(
            panel_outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_outputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panel_outputLayout.setVerticalGroup(
            panel_outputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_outputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1009, 432));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_browseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browseFileActionPerformed
        

        // Load files
        
        final JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("XML FILES", "xml");
        jFileChooser.setFileFilter(filter);
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (lastOpenedFile != null) {
            jFileChooser.setCurrentDirectory(lastOpenedFile);
        }
        jFileChooser.setMultiSelectionEnabled(true);
        jFileChooser.setPreferredSize(new Dimension(700, 500));
        jFileChooser.showOpenDialog(this);
        
        //Read files
        FileReader fileReader = new FileReader();
        ArrayList<File> selectedFiles_new = new ArrayList<File>();
        
        File[] files = jFileChooser.getSelectedFiles();      
        File f = files[0];
        lastOpenedFile = f;
        if (f.exists() && f.isDirectory()) {
            fileReader.listFilesForFolder(f, selectedFiles_new);
        }else{
            for(File file : files){
                selectedFiles_new.add(file);
            }
        }

        if (selectedFiles_new.size() > 0) {

            if (selectedFiles == null) {
                selectedFiles = new HashSet<File>();
            }

            int i = -1;
            for (File file : selectedFiles_new) {
                i++;
                boolean added = selectedFiles.add(file);
                if (!added) {
                    selectedFiles_new.remove(i);
                }
            }

            label_numFiles.setText(selectedFiles.size() + " files selected");
            label_numFiles.setVisible(true);
            btn_browseFile.setText("Add More Files");

            try{
            if (sentences == null) {
                sentences = fileReader.loadSentences(selectedFiles_new, null);
            } else {
                sentences = fileReader.loadSentences(selectedFiles_new, sentences);
            }
            }catch(RuntimeException e){
                e.printStackTrace();
            }
        }
        
        button_search.setEnabled(true);
        button_clearFiles.setEnabled(true);

    }//GEN-LAST:event_btn_browseFileActionPerformed

    private void button_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_searchActionPerformed
        // TODO add your handling code here:
        int window_size = (Integer) spinner_windowSize.getValue();
        String searchQuery = combo_search.getSelectedItem().toString();
        searchHandler searchHandler = new searchHandler();

        if (sentences != null) {
//            System.out.println("Search started");
            searchResults = searchHandler.searchQuery(searchQuery, sentences, window_size);
            displayOutput(searchResults);
        }
        combo_search.addItem(searchQuery);
    }//GEN-LAST:event_button_searchActionPerformed

    private void combo_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_searchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_combo_searchActionPerformed

    private void button_clearFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_clearFilesActionPerformed
        setInitState();  
    }//GEN-LAST:event_button_clearFilesActionPerformed

    void displayOutput(DataModel searchResults) {
        panel_output.setVisible(true);
        table_output.setModel(searchResults);
        label_numHits.setText("Number of Hits: "+searchResults.getSize() + "");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_browseFile;
    private javax.swing.JButton button_clearFiles;
    private javax.swing.JButton button_search;
    private javax.swing.JComboBox<String> combo_search;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_numFiles;
    private javax.swing.JLabel label_numHits;
    private javax.swing.JPanel panel_output;
    private javax.swing.JSpinner spinner_windowSize;
    private javax.swing.JTable table_output;
    // End of variables declaration//GEN-END:variables
}
